package lexer

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestLexer(t *testing.T) {
	lexer := NewContentLexer(`package ▶entity_name◀

import (
	"github.com/uptrace/bun"
	"▶service-name◀-service/▶service-name◀-shared/dto"
)

type Model▶EntityName◀ struct {
	bun.BaseModel ` + "`" + `bun:"Table:▶⬇Entity➡NameDb◀"` + "`" + `

⏩	▶⬇AttributeName◀ ▶⬇Attribute➡Nullable↔*◀▶⬇Attribute➡TypeGo◀ ` + "`" + `bun:"▶⬇Attribute➡NameDb◀▶⬇Attribute➡PrimaryKey↔,pk◀" maker:"type_db:▶⬇Attribute➡TypeDb◀▶,default:▶⬇Attribute➡Default◀◀▶,fk:▶⬇Attribute➡FkTable◀|▶⬇Attribute➡FkColumn◀◀"` + "`" + `⏪
}

func (m *Model▶EntityName◀) To▶EntityName◀() dto.▶EntityName◀ {
	return dto.▶EntityName◀{
⏩		▶AttributeName◀: m.▶AttributeName◀,⏪
	}
}
`)

	var actual []Token
	for {
		token := lexer.NextToken()
		if token == nil {
			break
		}
		actual = append(actual, token)
	}

	assert.Equal(
		t,
		[]Token{
			Word("package"),
			Separator(" "),
			TemplateStart("▶"),
			Word("entity_name"),
			TemplateEnd("◀"),
			LineFeed(2),
			Word("import"),
			Separator(" "),
			Word("("),
			LineFeed(1),
			Separator("\t"),
			Word(`"github.com/uptrace/bun"`),
			LineFeed(1),
			Separator("\t"),
			Word(`"`),
			TemplateStart("▶"),
			Word("service-name"),
			TemplateEnd("◀"),
			Word("-service/"),
			TemplateStart("▶"),
			Word("service-name"),
			TemplateEnd("◀"),
			Word(`-shared/dto"`),
			LineFeed(1),
			Word(")"),
			LineFeed(2),
			Word("type"),
			Separator(" "),
			Word("Model"),
			TemplateStart("▶"),
			Word("EntityName"),
			TemplateEnd("◀"),
			Separator(" "),
			Word("struct"),
			Separator(" "),
			Word("{"),
			LineFeed(1),
			Separator("\t"),
			Word("bun.BaseModel"),
			Separator(" "),
			Word("`bun:\"Table:"),
			TemplateStart("▶"),
			TemplateKey("⬇"),
			Word("Entity"),
			TemplateSeparator("➡"),
			Word("NameDb"),
			TemplateEnd("◀"),
			Word("\"`"),
			LineFeed(2),
			TemplateChildStart("⏩"),
			Separator("\t"),
			TemplateStart("▶"),
			TemplateKey("⬇"),
			Word("AttributeName"),
			TemplateEnd("◀"),
			Separator(" "),
			TemplateStart("▶"),
			TemplateKey("⬇"),
			Word("Attribute"),
			TemplateSeparator("➡"),
			Word("Nullable"),
			TemplateCondition("↔"),
			Word("*"),
			TemplateEnd("◀"),
			TemplateStart("▶"),
			TemplateKey("⬇"),
			Word("Attribute"),
			TemplateSeparator("➡"),
			Word("TypeGo"),
			TemplateEnd("◀"),
			Separator(" "),
			Word("`bun:\""),
			TemplateStart("▶"),
			TemplateKey("⬇"),
			Word("Attribute"),
			TemplateSeparator("➡"),
			Word("NameDb"),
			TemplateEnd("◀"),
			TemplateStart("▶"),
			TemplateKey("⬇"),
			Word("Attribute"),
			TemplateSeparator("➡"),
			Word("PrimaryKey"),
			TemplateCondition("↔"),
			Word(",pk"),
			TemplateEnd("◀"),
			Word("\""),
			Separator(" "),
			Word(`maker:"type_db:`),
			TemplateStart("▶"),
			TemplateKey("⬇"),
			Word("Attribute"),
			TemplateSeparator("➡"),
			Word("TypeDb"),
			TemplateEnd("◀"),
			TemplateStart("▶"),
			Word(",default:"),
			TemplateStart("▶"),
			TemplateKey("⬇"),
			Word("Attribute"),
			TemplateSeparator("➡"),
			Word("Default"),
			TemplateEnd("◀"),
			TemplateEnd("◀"),
			TemplateStart("▶"),
			Word(",fk:"),
			TemplateStart("▶"),
			TemplateKey("⬇"),
			Word("Attribute"),
			TemplateSeparator("➡"),
			Word("FkTable"),
			TemplateEnd("◀"),
			Word("|"),
			TemplateStart("▶"),
			TemplateKey("⬇"),
			Word("Attribute"),
			TemplateSeparator("➡"),
			Word("FkColumn"),
			TemplateEnd("◀"),
			TemplateEnd("◀"),
			Word("\"`"),
			TemplateChildEnd("⏪"),
			LineFeed(1),
			Word("}"),
			LineFeed(2),
			Word("func"),
			Separator(" "),
			Word("(m"),
			Separator(" "),
			Word("*Model"),
			TemplateStart("▶"),
			Word("EntityName"),
			TemplateEnd("◀"),
			Word(")"),
			Separator(" "),
			Word("To"),
			TemplateStart("▶"),
			Word("EntityName"),
			TemplateEnd("◀"),
			Word("()"),
			Separator(" "),
			Word("dto."),
			TemplateStart("▶"),
			Word("EntityName"),
			TemplateEnd("◀"),
			Separator(" "),
			Word("{"),
			LineFeed(1),
			Separator("\t"),
			Word("return"),
			Separator(" "),
			Word("dto."),
			TemplateStart("▶"),
			Word("EntityName"),
			TemplateEnd("◀"),
			Word("{"),
			LineFeed(1),
			TemplateChildStart("⏩"),
			Separator("\t\t"),
			TemplateStart("▶"),
			Word("AttributeName"),
			TemplateEnd("◀"),
			Word(":"),
			Separator(" "),
			Word("m."),
			TemplateStart("▶"),
			Word("AttributeName"),
			TemplateEnd("◀"),
			Word(","),
			TemplateChildEnd("⏪"),
			LineFeed(1),
			Separator("\t"),
			Word("}"),
			LineFeed(1),
			Word("}"),
			LineFeed(1),
		},
		actual,
	)
}
